// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://atjsuibqpdesqzdbosbe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF0anN1aWJxcGRlc3F6ZGJvc2JlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NDE0MTAsImV4cCI6MjA2NTUxNzQxMH0.0Xt4URmmeVX81Pm-jjnYbLhM4yMOP_SkHZAtdNhRchE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);