// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xoslwwobgjddkzbcaezh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhvc2x3d29iZ2pkZGt6YmNhZXpoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MDk1OTgsImV4cCI6MjA2NTQ4NTU5OH0.XT3gUfViWaZc2H4AXl62js1_qdwkxUe1qGpxCj-Az6A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);